# utils/config.py

DEFAULT_SYMBOLS = ["btcusdt", "ethusdt"]

DEFAULT_TIMEFRAME = "5m"
DEFAULT_ROLLING_WINDOW = 50

DEFAULT_Z_ALERT_THRESHOLD = 2.0
DEFAULT_BACKTEST_ENTRY_Z = 2.0

SUPPORTED_TIMEFRAMES = ["1s", "1m", "5m"]
